# Generated by Django 3.1.3 on 2020-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Oldal név')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Alcím')),
                ('footer', models.CharField(max_length=200, verbose_name='Lábléc')),
            ],
        ),
    ]
