# Generated by Django 3.1.3 on 2020-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201111_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logo', verbose_name='Logo'),
        ),
    ]
