# Generated by Django 3.1.3 on 2020-11-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201118_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='siteinfo',
            old_name='logo',
            new_name='image',
        ),
    ]
